import type { Metadata } from "next";
import "../../styles/globals.css";

import { kanit300 } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit300.className}>{children}</body>
    </html>
  );
}
